import torch
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer("all-MiniLM-L6-v2")

positions = [
    "Goalie (GK): The goalkeeper is the only player allowed to handle the ball within the penalty area and serves as the last line of defense. Their primary job is to prevent goals by stopping shots using any part of the body, commanding the box during crosses or set pieces, and organizing the defensive line. Modern goalkeepers must have excellent reflexes, agility, anticipation, and distribution skills. They are also expected to contribute to buildup play by making accurate short and long passes, often acting as a 'sweeper-keeper' to clear through balls or start counter-attacks. Communication, decision-making under pressure, and aerial dominance are key components of elite goalkeeping, especially in high defensive lines and pressing systems.",
    "Center Back (CB): Center backs are the core of the defensive unit, positioned centrally in front of the goalkeeper. They are responsible for stopping opposition forwards through tackling, blocking shots, intercepting passes, and winning aerial duels. In most formations, two center backs work as a pair, requiring strong coordination and understanding. Modern CBs are not only physical enforcers but also key to progressing the ball from the back through line-breaking passes. Tactical awareness, composure in possession, and the ability to read the game are essential. In zonal and man-marking systems, CBs are often matched up against target strikers and must remain disciplined while maintaining the defensive shape. Many also assume leadership roles, organizing the backline and stepping up to initiate pressing triggers.",
    "Right Back (RB): Right backs defend the right side of the pitch and are responsible for stopping opposing wingers from advancing into dangerous areas. In modern football, RBs also contribute heavily to the attack through overlapping runs, underlapping support, and accurate crosses into the box. They need to be fast, have high stamina, and be capable of covering long distances repeatedly. Depending on the tactical setup, some right backs invert into midfield during possession to help overload central areas, while others provide consistent width. They also press high or track back to cover counters and must be comfortable in both 1v1 defending and passing in tight spaces.",
    "Left Back (LB): Left backs function similarly to right backs but operate on the left flank. Their role is to neutralize opposition wide players, provide width during attacking phases, and support transitions on both sides of the ball. Modern LBs often function as hybrid players, combining defensive solidity with offensive contribution. They may overlap a left winger, deliver crosses, or invert into midfield in positional play systems. Tactical intelligence, crossing accuracy, and defensive recovery speed are vital. Elite left backs contribute to attacking buildup, press traps, and are expected to participate in both sustained possession and counter-pressing phases.",
    "Central Defensive Midfielder (CDM): The CDM acts as the tactical anchor of the midfield, positioned just in front of the center backs. They are primarily responsible for screening the defense by intercepting passes, making tackles, and breaking up opposition play. Beyond defense, CDMs facilitate smooth transitions into attack through simple or progressive passes. Their positioning is crucial for maintaining team structure, providing an outlet under pressure, and offering balance when full-backs push forward. In pressing systems, the CDM often covers central gaps or shifts wide to support ball-side overloads. They are typically among the most tactically disciplined players, with strong anticipation, spatial awareness, and stamina. CDMs vary from destroyers (ball-winners) to deep-lying playmakers who dictate tempo and switch the point of attack.",
    "Central Attacking Midfielder (CAM): CAMs operate in advanced midfield areas, just behind the striker(s), and are tasked with unlocking defenses through creativity, vision, and precise passing. They thrive in tight spaces, combining with forwards and wide players to create goal-scoring chances. CAMs often make third-man runs into the box, take shots from distance, and receive the ball between opposition lines. In pressing schemes, they may mark defensive midfielders or trigger pressure in central areas. CAMs must balance flair with discipline, contribute to quick transitions, and read defensive weaknesses to exploit space. They are often the most technically gifted players, responsible for dictating play in the final third and maintaining fluidity in attacking movements.",
    "Central Midfielder (CM): CMs are box-to-box players who perform both defensive and offensive duties throughout the match. They link the backline to the attacking unit, recycle possession, and dictate the pace of the game. CMs cover large areas of the pitch, intercept passes, support pressing efforts, and contribute to buildup with forward passes and late runs into the box. They often assist in defensive duties when the team is out of possession, and provide numerical superiority in the middle of the park. Versatility, tactical intelligence, and high work rate are key attributes. Depending on the tactical setup, CMs may operate more defensively (as a shuttler or pivot) or more offensively (as a roaming creator).",
    "Left Winger (LW): Left wingers are positioned high and wide on the left side, providing width, penetration, and goal-scoring threats. They must be excellent dribblers, quick over short and long distances, and able to deliver accurate crosses or cut inside to shoot. LWs often isolate full-backs in 1v1 situations or exploit spaces created by overlapping full-backs. In modern systems, they are expected to press from the front, track back to defend, and rotate with other attackers to disrupt defensive lines. Whether traditional (staying wide) or inverted (cutting inside onto their stronger foot), LWs must read game flows, make well-timed runs, and finish when presented with chances.",
    "Right Winger (RW): Right wingers mirror the responsibilities of left wingers on the opposite flank. They are tasked with stretching defenses, advancing the ball in wide areas, and delivering balls into the penalty box. RWs need excellent speed, tight ball control, and quick decision-making in the final third. They may switch flanks, combine with overlapping full-backs, or cut inside to shoot, depending on their dominant foot and tactical instructions. Defensively, they contribute by pressing opposition full-backs and covering wide channels. RWs are vital in both possession-based and transition-oriented systems, especially when tasked with exploiting mismatches in wide zones.",
    "Striker (ST): The striker is the team’s primary goal-scorer and the focal point of attacking play. Positioned furthest forward, they are expected to convert chances inside and outside the box. STs make intelligent runs behind defenders, hold up the ball under pressure, and finish with accuracy and composure. There are various striker archetypes — from target men who dominate aerial duels, to poachers who rely on positioning and reaction, to false nines who drop deep to link play and create space for others. Strikers must be tactically sharp to time their movements, stretch defenses, and adapt to different phases of play. In pressing teams, strikers also lead the press and initiate ball recovery efforts in the final third."
]

positions_embedder = model.encode(positions, convert_to_tensor=True)

query = input("Ask your question about a position: ")
query_embedding = model.encode(query, convert_to_tensor=True)

similarity_scores = util.cos_sim(query_embedding, positions_embedder)[0]
top_k = min(3, len(positions))
scores, indices = torch.topk(similarity_scores, k=top_k)

print("Query:", query)
print("Top matching sentence(s):")
for score, idx in zip(scores, indices):
    print(positions[idx], f"(Score: {score:.4f})")
